name: Release

on:
  push:
    branches: [main]

env:
  CONTAINER_IMAGE: chr0nu5/base:johnflix-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Build
        env:
          REACT_APP_API_URL: ${{ secrets.API_URL }}
          NODE_ENV: production
        run: |
          npm install
          npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOC_HUB_USR }}
          password: ${{ secrets.DOC_HUB_PWD }}

      - name: Build and tag the image
        run: |
          docker build . --file Dockerfile --tag $CONTAINER_IMAGE

      - name: Push the image
        run: |
          docker push $CONTAINER_IMAGE
